### ISSUE TITLE
Opening settings by clicking app icon

### ISSUE THREAD

**Issue by clouedoc** [vzakharov/komple#1]
Hi,

I could not open the settings on my Mac with the provided key combination (CMD+K).

I suggest that the settings box should appear when clicking the extensions' icon, like most other extensions.

(note: I'm just dumping ideas here; don't worry, I'm not expecting you to implement my feature requests 🙂 ).

**Comment by vzakharov** [comment]
Hey, thanks for the feedback! This has alway been the plan, but I had to figure out how to use Vue for the settings page first. I've just pushed an update that should add this feature. Let me know if it works for you!

**Comment by clouedoc** [comment]
I can confirm that your modifications work as intended. Your extension is so much fun! I'm eager to start writing blog posts about random topics online 😄 . Too bad my mother tongue is not English!
