### ISSUE TITLE
Documentation: listing API providers

### ISSUE THREAD

**Issue by clouedoc** [vzakharov/komple#2]
Hi (again).

There are multiple word-generation models out here, and also providers.

I believe your extension is using an OpenAI API format.

Here's one provider that provides OpenAI-compatible APIs for text generation, with alternative models: https://goose.ai/

**Comment by vzakharov** [comment]
Hey, you can actually use any provider you want (I use three).

To do this, you need to configure it in the settings page in the “API” and “Generation parameters” tabs of the (newly made) settings page:
![image](https://user-images.githubusercontent.com/188197/167700794-c9348afc-8b82-4773-8bbf-c856d0ad1257.png)
![image](https://user-images.githubusercontent.com/188197/167700806-bb4b6476-f1df-49c2-9fb3-09cada2bec12.png)

**Comment by clouedoc** [comment]
Your new UI works wonder ! Thank you !
